apiVersion: v1
kind: Service
metadata:
  name: grade-service
spec:
  type: ClusterIP  # Exposes the service within the cluster
  selector:
    app: grade-service  # Matches the app label in the Deployment
  ports:
    - protocol: TCP
      port: 80           # Port on which the service is exposed
      targetPort: 3001   # Port on the container the service forwards requests to
